services:
  postgres:
    image: postgres:16-alpine
    container_name: negotiator-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: negotiator-backend
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: negotiator-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
